/*
 *
 * WelcomePage constants
 *
 */

export const FETCH_QUICK_MODULES_LIST = 'app/WelcomePage/FETCH_QUICK_MODULES_LIST'
export const FETCH_QUICK_MODULES_LIST_SUCCESS = 'app/WelcomePage/FETCH_QUICK_MODULES_LIST_SUCCESS'
export const FETCH_QUICK_MODULES_LIST_FAILURE = 'app/WelcomePage/FETCH_QUICK_MODULES_LIST_FAILURE'
export const FETCH_USER_COINS = 'app/FETCH_USER_COINS'
export const FETCH_USER_COINS_SUCCESS = 'app/FETCH_USER_COINS_SUCCESS'
